#!/bin/bash

cat << "EOF"


    /$$$$$$                                                      /$$                      /$$$$$$$$      /$$          /$$         
   /$$__  $$                                                    | $$                     |__  $$__/     |__/         |__/         
  | $$  \__/ /$$$$$$  /$$$$$$  /$$$$$$  /$$$$$$ /$$$$$$  /$$$$$$| $$$$$$$ /$$   /$$         | $$ /$$$$$$ /$$/$$    /$$/$$ /$$$$$$ 
  | $$ /$$$$/$$__  $$/$$__  $$/$$__  $$/$$__  $|____  $$/$$__  $| $$__  $| $$  | $$         | $$/$$__  $| $|  $$  /$$| $$|____  $$
  | $$|_  $| $$$$$$$| $$  \ $| $$  \ $| $$  \__//$$$$$$| $$  \ $| $$  \ $| $$  | $$         | $| $$  \__| $$\  $$/$$/| $$ /$$$$$$$
  | $$  \ $| $$_____| $$  | $| $$  | $| $$     /$$__  $| $$  | $| $$  | $| $$  | $$         | $| $$     | $$ \  $$$/ | $$/$$__  $$
  |  $$$$$$|  $$$$$$|  $$$$$$|  $$$$$$| $$    |  $$$$$$| $$$$$$$| $$  | $|  $$$$$$$         | $| $$     | $$  \  $/  | $|  $$$$$$$
   \______/ \_______/\______/ \____  $|__/     \_______| $$____/|__/  |__/\____  $$         |__|__/     |__/   \_/   |__/\_______/
                              /$$  \ $$                | $$               /$$  | $$                                               
                             |  $$$$$$/                | $$              |  $$$$$$/                                               
                              \______/                 |__/               \______/                                                


EOF


# -----------------------------------------------------------------------------------------

echo "Welcome to Geography Trivia, a game to test your worldliness!"
sleep 2s
echo "Here's how it works:"
sleep 2s
echo
echo "* You will be presented a question and alotted 6 seconds to read the quesion."
sleep 2s
echo "* All questions will be either [t]rue or [f]alse. Select the appropriate letter for the answer."
sleep 2s
echo "* After reading the question, you will have 10 seconds to choose the correct answer."
sleep 3s
echo
echo "Ready, player?"
sleep 3s
echo

declare -i score
score=0
# QUESTION1

question1='QUESTION 1: Pennsylvania is the only American state to begin with the letter "p" [T/f]?'
for (( i=0; i<${#question1}; i++ ));
do
echo -n "${question1:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 1

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "Great Job!\n"
			let score++
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "Wrong!\n"
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION 2

question2="QUESTION 2: Johannesburg is one of South Africa's three capitals. [T/f]?"
for ((  i=0; i<${#question2}; i++ ));
do
echo -n "${question2:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 2

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "Nope! The capitals are actually Pretoria, Cape Town, and Bloemfontein.\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "That is correct!\n"
			let score++
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION 3

question3="QUESTION 3: Memphis is the state capital of Tennessee. [T/f]?"
for ((  i=0; i<${#question3}; i++ ));
do
echo -n "${question3:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 3

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "NO! The capital is Nashville.\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "You are correct!\n"
			let score++
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION 4

question4="QUESTION 4: Seattle is more northernly than New York City. [T/f]?"
for ((  i=0; i<${#question4}; i++ ));
do
echo -n "${question4:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "Great Job!\n"
			let score++
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "Nope!\n"
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION5

question5='QUESTION 5: There are 50 states in the contiguous United States. [T/f]?'
for (( i=0; i<${#question5}; i++ ));
do
echo -n "${question5:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 1

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "That's incorrect!\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "That's correct! Nice work.\n"
			let score++
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION6

question6='QUESTION 6: The Indian Ocean is the third largest ocean in the world. [T/f]?'
for (( i=0; i<${#question6}; i++ ));
do
echo -n "${question6:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 1

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "whohoo you got it.\n"
			let score++
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e ":( :( :( - incorrect.\n"
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION7

question7='QUESTION 7: The Mississippi River is the longest river in the world. [T/f]?'
for (( i=0; i<${#question7}; i++ ));
do
echo -n "${question7:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 1

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "That's incorrect! :( \n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e ":) :) :) - correct.\n"
			let score++
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION8

question8='QUESTION 8: The three countries with the largest land area in the world are Russia, Canada, and the United States. [T/f]?'
for (( i=0; i<${#question8}; i++ ));
do
echo -n "${question8:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 1

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "Incorrect Answer\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "correct answer ^_^\n"
			let score++
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION9

question9='QUESTION 9: The Tropic of Cancer is a meridian. [T/f]?'
for (( i=0; i<${#question9}; i++ ));
do
echo -n "${question9:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 1

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e ":( :( :( - incorrect.\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "That's correct! Nice work.\n"
			let score++
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION10

lastQ="Okay, last question."
for ((  i=0; i<${#lastQ}; i++ ));
do
echo -n "${lastQ:$i:1}"
sleep 0.08s
done
sleep 1s
echo
echo

question10='QUESTION 10: Uruguay has a greater population than Paraguay ? [T/f]?'
for (( i=0; i<${#question10}; i++ ));
do
echo -n "${question10:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 1

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "Nope. This is incorrect.\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "Great Job! ^_^ \n"
			let score++
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

#-----------------------------------------------------------------------------------------

sleep 2s

prompt1="Thanks for playing! I hope you had fun and maybe learned a thing or two."
for ((  i=0; i<${#prompt1}; i++ ));
do
echo -n "${prompt1:$i:1}"
sleep 0.06s
done
echo

sleep 2s

showScore="Your final score is $score"
for(( i=0; i<${#showScore}; i++));
do
echo -n "${showScore:$i:1}"
sleep 0.06s
done
echo

sleep 2s

prompt2="Take care, this is GAME OVER!"
for ((  i=0; i<${#prompt2}; i++ ));
do
echo -n "${prompt2:$i:1}"
sleep 0.06s
done
echo
sleep 2s
