#!/bin/bash

cat << "EOF"


    /$$$$$$                                                      /$$                      /$$$$$$$$      /$$          /$$         
   /$$__  $$                                                    | $$                     |__  $$__/     |__/         |__/         
  | $$  \__/ /$$$$$$  /$$$$$$  /$$$$$$  /$$$$$$ /$$$$$$  /$$$$$$| $$$$$$$ /$$   /$$         | $$ /$$$$$$ /$$/$$    /$$/$$ /$$$$$$ 
  | $$ /$$$$/$$__  $$/$$__  $$/$$__  $$/$$__  $|____  $$/$$__  $| $$__  $| $$  | $$         | $$/$$__  $| $|  $$  /$$| $$|____  $$
  | $$|_  $| $$$$$$$| $$  \ $| $$  \ $| $$  \__//$$$$$$| $$  \ $| $$  \ $| $$  | $$         | $| $$  \__| $$\  $$/$$/| $$ /$$$$$$$
  | $$  \ $| $$_____| $$  | $| $$  | $| $$     /$$__  $| $$  | $| $$  | $| $$  | $$         | $| $$     | $$ \  $$$/ | $$/$$__  $$
  |  $$$$$$|  $$$$$$|  $$$$$$|  $$$$$$| $$    |  $$$$$$| $$$$$$$| $$  | $|  $$$$$$$         | $| $$     | $$  \  $/  | $|  $$$$$$$
   \______/ \_______/\______/ \____  $|__/     \_______| $$____/|__/  |__/\____  $$         |__|__/     |__/   \_/   |__/\_______/
                              /$$  \ $$                | $$               /$$  | $$                                               
                             |  $$$$$$/                | $$              |  $$$$$$/                                               
                              \______/                 |__/               \______/                                                


EOF


# -----------------------------------------------------------------------------------------

echo "Welcome to Geography Trivia, a game to test your worldliness!"
sleep 2s
echo "Here's how it works:"
sleep 2s
echo
echo "* You will be presented a question and alotted 6 seconds to read the quesion."
sleep 2s
echo "* All questions will be either [t]rue or [f]alse. Select the appropriate letter for the answer."
sleep 2s
echo "* After reading the question, you will have 10 seconds to choose the correct answer."
sleep 3s
echo
echo "Ready, player?"
sleep 3s
echo


# QUESTION1

question1='QUESTION 1: Pennsylvania is the only American state to begin with the letter "p" [T/f]?'
for (( i=0; i<${#question1}; i++ ));
do
echo -n "${question1:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 1

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "Great Job!\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "Wrong!\n"
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION 2

question2="QUESTION 2: Johannesburg is one of South Africa's three capitals. [T/f]?"
for ((  i=0; i<${#question2}; i++ ));
do
echo -n "${question2:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 2

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "Nope! The capitals are actually Pretoria, Cape Town, and Bloemfontein.\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "That is correct!\n"
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION 3

question3="QUESTION 3: Memphis is the state capital of Tennessee. [T/f]?"
for ((  i=0; i<${#question3}; i++ ));
do
echo -n "${question3:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT 3

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "NO! The capital is Nashville.\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "You are correct!\n"
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

# QUESTION 4

lastQ="Okay, last question."
for ((  i=0; i<${#lastQ}; i++ ));
do
echo -n "${lastQ:$i:1}"
sleep 0.08s
done
sleep 1s
echo
echo

question4="QUESTION 4: Seattle is more northernly than New York City. [T/f]?"
for ((  i=0; i<${#question4}; i++ ));
do
echo -n "${question4:$i:1}"
sleep 0.08s
done
sleep 1s

# TIMER & READ INPUT

timeout=10
echo -e -n "\nTIMER:"
while [ $timeout -gt 0 ]; do
	echo -n " $timeout"
	if read -n1 -t1 -r -s input; then
		if [[ $input == "t" || $input == "T" ]]; then
			echo -e "\ntrue"
			sleep 1s
			echo -e "Great Job!\n"
		else
			echo -e "\nfalse"
			sleep 1s
			echo -e "Nope!\n"
		fi
		echo
		break
	fi
		let timeout--
done
if [ $timeout -eq 0 ]; then
	echo -e "\nTime's up! Better luck next time.\n"
fi

#-----------------------------------------------------------------------------------------

sleep 2s

prompt1="Thanks for playing! I hope you had fun and maybe learned a thing or two."
for ((  i=0; i<${#prompt1}; i++ ));
do
echo -n "${prompt1:$i:1}"
sleep 0.06s
done
echo

sleep 2s

prompt2="Take care, this is GAME OVER!"
for ((  i=0; i<${#prompt2}; i++ ));
do
echo -n "${prompt2:$i:1}"
sleep 0.06s
done
echo
sleep 2s
